package expert.detection
 

import expert.model.Mesure;
import expert.model.Configuration;
import expert.output.Pente; 
 
rule "detection pente "
salience 103
    when
        //tester si l'angle de la pente est entre la valeur minimale et moyenne
        m : Mesure( alpha > Configuration.penteSeuilMin)
    then

        insert(new Pente(m.getLatitude(), m.getLongitude(), m.getAlpha() ,m.getDate()));
end


query "extract Pente minimale"
	
	pente : Pente( severite > Configuration.penteSeuilMin && < Configuration.penteSeuilMoy )
end

query "extract Pente moyenne"
	
	pente : Pente( severite > Configuration.penteSeuilMoy && < Configuration.penteSeuilMax )
end

query "extract Pente maximale"
	
	pente : Pente( severite > Configuration.penteSeuilMax )
end

query "extract all Pente"
	
	pente : Pente()
end

query "fetch for a Pente at longit and lat"(double lat,double longit)
	pente : Pente( longitude == longit && latitude == lat )
end